/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_kkp;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author Jamaludin Septian
 */
public class HalamanKendaraan extends javax.swing.JFrame {
   private final  Connection conn = new koneksi().connect();
   private DefaultTableModel tabmode;
   private int baris;

    /**
     * Creates new form HalamanKendaraan
     */
    public HalamanKendaraan() {
        initComponents();
        setLocationRelativeTo(this);
        datatable();
        backgroundTransparent();
        
    }
    
    
    protected void kosong(){
        tkendaraan.setText("");
        tmerek.setText("");
        tmodel.setText("");
        tnik.setText("");
        tjenis.setText("");
        twarna.setText("");
        tpemilik.setText("");
        tplat.setText("");
    }
    protected void datatable(){
        Object[] Baris = {"ID Kendaraan", "Merek", "Model", "NIK", "Jenis", "Warna", "Pemilik", "Plat"};
        tabmode = new DefaultTableModel(null, Baris);
        tabelBarang.setModel(tabmode);
        String sql = "SELECT * FROM tbl_kendaraan";
       try {
           java.sql.Statement stat = conn.createStatement();
           ResultSet hasil = stat.executeQuery(sql);
           while(hasil.next()){
                String a = hasil.getString("idKendaraan");
                String b = hasil.getString("merek");
                String c = hasil.getString("model");
                String d = hasil.getString("nik");
                String e = hasil.getString("jenis");
                String f = hasil.getString("warna");
                String g = hasil.getString("pemilik");
                String h = hasil.getString("platNomor");
                String[] data = {a,b,c,d,e,f,g,h};
                tabmode.addRow(data);
            }
       } catch (SQLException ex) {
           Logger.getLogger(HalamanAdmin.class.getName()).log(Level.SEVERE, null, ex);
       }
            
    }
    
    
    private void backgroundTransparent(){
        tkendaraan.setBackground(new java.awt.Color(0,0,0,1));
        tkendaraan.requestFocus();
        tmerek.setBackground(new java.awt.Color(0,0,0,1));
        tmodel.setBackground(new java.awt.Color(0,0,0,1));
        tnik.setBackground(new java.awt.Color(0,0,0,1));
        tjenis.setBackground(new java.awt.Color(0,0,0,1));
        twarna.setBackground(new java.awt.Color(0,0,0,1));
        tpemilik.setBackground(new java.awt.Color(0,0,0,1));
        tplat.setBackground(new java.awt.Color(0,0,0,1));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tplat = new javax.swing.JTextField();
        tpemilik = new javax.swing.JTextField();
        twarna = new javax.swing.JTextField();
        tjenis = new javax.swing.JTextField();
        tnik = new javax.swing.JTextField();
        tmodel = new javax.swing.JTextField();
        tmerek = new javax.swing.JTextField();
        tkendaraan = new javax.swing.JTextField();
        btnkosongkan = new javax.swing.JLabel();
        btncetak = new javax.swing.JLabel();
        btnhapus = new javax.swing.JLabel();
        btnubah = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnsimpan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBarang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tplat.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        tplat.setForeground(new java.awt.Color(255, 255, 255));
        tplat.setBorder(null);
        tplat.setOpaque(false);
        jPanel1.add(tplat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 433, 210, 20));

        tpemilik.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        tpemilik.setForeground(new java.awt.Color(255, 255, 255));
        tpemilik.setBorder(null);
        tpemilik.setOpaque(false);
        jPanel1.add(tpemilik, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 392, 210, 20));

        twarna.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        twarna.setForeground(new java.awt.Color(255, 255, 255));
        twarna.setBorder(null);
        twarna.setOpaque(false);
        jPanel1.add(twarna, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 352, 210, 20));

        tjenis.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        tjenis.setForeground(new java.awt.Color(255, 255, 255));
        tjenis.setBorder(null);
        tjenis.setOpaque(false);
        jPanel1.add(tjenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 311, 210, 20));

        tnik.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        tnik.setForeground(new java.awt.Color(255, 255, 255));
        tnik.setBorder(null);
        tnik.setOpaque(false);
        jPanel1.add(tnik, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 210, 20));

        tmodel.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        tmodel.setForeground(new java.awt.Color(255, 255, 255));
        tmodel.setBorder(null);
        tmodel.setOpaque(false);
        jPanel1.add(tmodel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 210, 20));

        tmerek.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        tmerek.setForeground(new java.awt.Color(255, 255, 255));
        tmerek.setBorder(null);
        tmerek.setOpaque(false);
        jPanel1.add(tmerek, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 210, 20));

        tkendaraan.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        tkendaraan.setForeground(new java.awt.Color(255, 255, 255));
        tkendaraan.setBorder(null);
        tkendaraan.setOpaque(false);
        jPanel1.add(tkendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 210, 20));

        btnkosongkan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnkosongkanMouseClicked(evt);
            }
        });
        jPanel1.add(btnkosongkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 70, 30));
        jPanel1.add(btncetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 70, 30));

        btnhapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhapusMouseClicked(evt);
            }
        });
        jPanel1.add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 70, 30));

        btnubah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnubahMouseClicked(evt);
            }
        });
        jPanel1.add(btnubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 70, 30));

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        btnsimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsimpanMouseClicked(evt);
            }
        });
        jPanel1.add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 70, 30));

        jScrollPane1.setOpaque(false);

        tabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelBarang);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 700, 480));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/HalamanKendaraan.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1068, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        new HalamanDepan().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btnsimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsimpanMouseClicked
        // TODO add your handling code here:
        String sql = "INSERT INTO tbl_kendaraan VALUES (?,?,?,?,?,?,?,?,?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, tkendaraan.getText());
            stat.setString(2, tmerek.getText());
            stat.setString(3, tmodel.getText());
            stat.setString(4, tnik.getText());
            stat.setString(5, tjenis.getText());
            stat.setString(6, twarna.getText());
            stat.setString(7, tpemilik.getText());
            stat.setString(8, tplat.getText());
            stat.setString(9, "1");
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
            kosong();
            tkendaraan.requestFocus();
            datatable();
        } catch (SQLException ex) {
            Logger.getLogger(HalamanAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnsimpanMouseClicked

    private void btnubahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnubahMouseClicked
        // TODO add your handling code here:
        try {
            String sql = "UPDATE tbl_kendaraan set merek = ?, model=?, nik=?, jenis=?, warna=?, pemilik=?, platNomor=?, statusAktif=? where idKendaraan = ?";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, tmerek.getText());
            stat.setString(2, tmodel.getText());
            stat.setString(3, tnik.getText());
            stat.setString(4, tjenis.getText());
            stat.setString(5, twarna.getText());
            stat.setString(6, tpemilik.getText());
            stat.setString(7, tplat.getText());
            stat.setString(8, "1");
            stat.setString(9, tkendaraan.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil diubah");
            kosong();
            tkendaraan.requestFocus();
            datatable();
            btnsimpan.setEnabled(true);
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, "Data gagal diubah"+ex);
        }
    }//GEN-LAST:event_btnubahMouseClicked

    private void tabelBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBarangMouseClicked
        // TODO add your handling code here:
        int bar = tabelBarang.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();
        String g = tabmode.getValueAt(bar, 6).toString();
        String h = tabmode.getValueAt(bar, 7).toString();
        tkendaraan.setText(a);
        tmerek.setText(b);
        tmodel.setText(c);
        tnik.setText(d);
        tjenis.setText(e);
        twarna.setText(f);
        tpemilik.setText(g);
        tplat.setText(h);
        btnsimpan.setEnabled(false);
    }//GEN-LAST:event_tabelBarangMouseClicked

    private void btnhapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhapusMouseClicked
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "hapus", "Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0){
            try {
                PreparedStatement stat = conn.prepareStatement("DELETE FROM tbl_kendaraan WHERE idKendaraan = ?");
                String noNya = tkendaraan.getText();
                stat.setString(1, noNya);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                kosong();
                tkendaraan.requestFocus();
                datatable();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Data gagal dihapus"+ex);
            }
        }
    }//GEN-LAST:event_btnhapusMouseClicked

    private void btnkosongkanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkosongkanMouseClicked
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_btnkosongkanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanKendaraan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btncetak;
    private javax.swing.JLabel btnhapus;
    private javax.swing.JLabel btnkosongkan;
    private javax.swing.JLabel btnsimpan;
    private javax.swing.JLabel btnubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelBarang;
    private javax.swing.JTextField tjenis;
    private javax.swing.JTextField tkendaraan;
    private javax.swing.JTextField tmerek;
    private javax.swing.JTextField tmodel;
    private javax.swing.JTextField tnik;
    private javax.swing.JTextField tpemilik;
    private javax.swing.JTextField tplat;
    private javax.swing.JTextField twarna;
    // End of variables declaration//GEN-END:variables
}
