/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_kkp;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author Jamaludin Septian
 */
public class HalamanPengemudi extends javax.swing.JFrame {
   private final  Connection conn = new koneksi().connect();
   private DefaultTableModel tabmode;
   private int baris;

    /**
     * Creates new form HalamanPengemudi
     */
    public HalamanPengemudi() {
        initComponents();
        setLocationRelativeTo(this);
        datatable();
        backgroundTransparent();
    }
    
    
    protected void kosong(){
        tidpengemudi.setText("");
        tnama.setText("");
        buttonGroup1.clearSelection();
        ttgl.setText("");
        talamat.setText("");
        tnohp.setText("");
        tstatusaktif.setText("");
    }
    protected void datatable(){
        Object[] Baris = {"ID Pengemudi","Nama","Jenis Kelamin","Tanggal Lahir","Alamat","No HP","Status Aktif"};
        tabmode = new DefaultTableModel(null, Baris);
        tabelPengemudi.setModel(tabmode);
        String sql = "SELECT * FROM tbl_pengemudi";
       try {
           java.sql.Statement stat = conn.createStatement();
           ResultSet hasil = stat.executeQuery(sql);
           while(hasil.next()){
                String a = hasil.getString("idPengemudi");
                String b = hasil.getString("nama");
                String c = hasil.getString("jenisKelamin");
                String d = hasil.getString("tglLahir");
                String e = hasil.getString("alamat");
                String f = hasil.getString("noHp");
                String g = hasil.getString("statusAktif");
                String[] data = {a,b,c,d,e,f,g};
                tabmode.addRow(data);
            }
       } catch (SQLException ex) {
           Logger.getLogger(HalamanAdmin.class.getName()).log(Level.SEVERE, null, ex);
       }
            
    }
    
    
    private void backgroundTransparent(){
        tidpengemudi.setBackground(new java.awt.Color(0,0,0,1));
        tidpengemudi.requestFocus();
        tnama.setBackground(new java.awt.Color(0,0,0,1));
        talamat.setBackground(new java.awt.Color(0,0,0,1));
        ttgl.setBackground(new java.awt.Color(0,0,0,1));
        tnohp.setBackground(new java.awt.Color(0,0,0,1));
        tstatusaktif.setBackground(new java.awt.Color(0,0,0,1));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        talamat = new javax.swing.JTextField();
        ttgl = new javax.swing.JTextField();
        tstatusaktif = new javax.swing.JTextField();
        tnohp = new javax.swing.JTextField();
        tnama = new javax.swing.JTextField();
        tidpengemudi = new javax.swing.JTextField();
        btncetak = new javax.swing.JLabel();
        btnkosongkan = new javax.swing.JLabel();
        btnhapus = new javax.swing.JLabel();
        btnubah = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnsimpan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPengemudi = new javax.swing.JTable();
        rLk = new javax.swing.JRadioButton();
        rPr = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        talamat.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        talamat.setForeground(new java.awt.Color(255, 255, 255));
        talamat.setBorder(null);
        talamat.setOpaque(false);
        jPanel1.add(talamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 325, 210, 50));

        ttgl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        ttgl.setForeground(new java.awt.Color(255, 255, 255));
        ttgl.setBorder(null);
        ttgl.setOpaque(false);
        jPanel1.add(ttgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 285, 210, 20));

        tstatusaktif.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        tstatusaktif.setForeground(new java.awt.Color(255, 255, 255));
        tstatusaktif.setBorder(null);
        tstatusaktif.setOpaque(false);
        jPanel1.add(tstatusaktif, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 443, 210, 20));

        tnohp.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        tnohp.setForeground(new java.awt.Color(255, 255, 255));
        tnohp.setBorder(null);
        tnohp.setOpaque(false);
        jPanel1.add(tnohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 398, 210, 20));

        tnama.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        tnama.setForeground(new java.awt.Color(255, 255, 255));
        tnama.setBorder(null);
        tnama.setOpaque(false);
        jPanel1.add(tnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 195, 210, 20));

        tidpengemudi.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        tidpengemudi.setForeground(new java.awt.Color(255, 255, 255));
        tidpengemudi.setBorder(null);
        tidpengemudi.setOpaque(false);
        jPanel1.add(tidpengemudi, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 150, 210, 20));
        jPanel1.add(btncetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 70, 30));

        btnkosongkan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnkosongkanMouseClicked(evt);
            }
        });
        jPanel1.add(btnkosongkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 70, 30));

        btnhapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhapusMouseClicked(evt);
            }
        });
        jPanel1.add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 70, 30));

        btnubah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnubahMouseClicked(evt);
            }
        });
        jPanel1.add(btnubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 70, 30));

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        btnsimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsimpanMouseClicked(evt);
            }
        });
        jPanel1.add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 70, 30));

        tabelPengemudi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPengemudi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPengemudiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPengemudi);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 580, 480));

        rLk.setBackground(new java.awt.Color(194, 194, 194));
        buttonGroup1.add(rLk);
        rLk.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        rLk.setForeground(new java.awt.Color(255, 255, 255));
        rLk.setText("Laki - Laki");
        rLk.setContentAreaFilled(false);
        rLk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rLkActionPerformed(evt);
            }
        });
        jPanel1.add(rLk, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 243, 90, -1));

        rPr.setBackground(new java.awt.Color(194, 194, 194));
        buttonGroup1.add(rPr);
        rPr.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        rPr.setForeground(new java.awt.Color(255, 255, 255));
        rPr.setText("Perempuan");
        rPr.setContentAreaFilled(false);
        rPr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rPrActionPerformed(evt);
            }
        });
        jPanel1.add(rPr, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 243, 90, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/HalamanPengemudi.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        new HalamanDepan().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btnsimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsimpanMouseClicked
        // TODO add your handling code here:
        String sql = "INSERT INTO tbl_pengemudi VALUES (?,?,?,?,?,?,?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, tidpengemudi.getText());
            stat.setString(2, tnama.getText());
            String jk = "";
            if(rLk.isSelected()) jk = "Laki - Laki";
            else jk = "Perempuan";
            stat.setString(3, jk);
            stat.setString(4, ttgl.getText());
            stat.setString(5, talamat.getText());
            stat.setString(6, tnohp.getText());
            stat.setString(7, tstatusaktif.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
            kosong();
            tidpengemudi.requestFocus();
            datatable();
        } catch (SQLException ex) {
            Logger.getLogger(HalamanAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnsimpanMouseClicked

    private void btnubahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnubahMouseClicked
        // TODO add your handling code here:
        try {
            String sql = "UPDATE tbl_pengemudi set nama = ?, jenisKelamin=?,  tglLahir=?, alamat=?, noHp=?, statusAktif=? where idPengemudi = ?";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, tidpengemudi.getText());
            stat.setString(2, tnama.getText());
            String jk = "";
            if(rLk.isSelected()) jk = "Laki - Laki";
            else jk = "Perempuan";
            stat.setString(3, jk);
            stat.setString(4, ttgl.getText());
            stat.setString(5, talamat.getText());
            stat.setString(6, tnohp.getText());
            stat.setString(7, tstatusaktif.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil diubah");
            kosong();
            tidpengemudi.requestFocus();
            datatable();
            btnsimpan.setEnabled(true);
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, "Data gagal diubah"+ex);
        }
    }//GEN-LAST:event_btnubahMouseClicked

    private void tabelPengemudiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPengemudiMouseClicked
        // TODO add your handling code here:
        int bar = tabelPengemudi.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();
        String g = tabmode.getValueAt(bar, 6).toString();
        tidpengemudi.setText(a);
        tnama.setText(b);
        if(c.equals("Laki - Laki")){
            rLk.setSelected(true);
            rPr.setSelected(false);
        }else {
            rLk.setSelected(false);
            rPr.setSelected(true);
        }
        ttgl.setText(d);
        talamat.setText(e);
        tnohp.setText(f);
        tstatusaktif.setText(g);
        btnsimpan.setEnabled(false);
    }//GEN-LAST:event_tabelPengemudiMouseClicked

    private void btnhapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhapusMouseClicked
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "hapus", "Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0){
            try {
                PreparedStatement stat = conn.prepareStatement("DELETE FROM tbl_pengemudi WHERE idPengemudi = ?");
                String noNya = tidpengemudi.getText();
                stat.setString(1, noNya);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                kosong();
                tidpengemudi.requestFocus();
                datatable();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Data gagal dihapus"+ex);
            }
        }
    }//GEN-LAST:event_btnhapusMouseClicked

    private void rLkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rLkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rLkActionPerformed

    private void rPrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rPrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rPrActionPerformed

    private void btnkosongkanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkosongkanMouseClicked
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_btnkosongkanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanPengemudi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btncetak;
    private javax.swing.JLabel btnhapus;
    private javax.swing.JLabel btnkosongkan;
    private javax.swing.JLabel btnsimpan;
    private javax.swing.JLabel btnubah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rLk;
    private javax.swing.JRadioButton rPr;
    private javax.swing.JTable tabelPengemudi;
    private javax.swing.JTextField talamat;
    private javax.swing.JTextField tidpengemudi;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tnohp;
    private javax.swing.JTextField tstatusaktif;
    private javax.swing.JTextField ttgl;
    // End of variables declaration//GEN-END:variables
}
